config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  root 'weathers#index'

  devise_scope :user do
    get "mypage/:id", :to => "users/confirmations#show", as: 'mypage'
    get "profile_edit", :to => "users/registrations#profile_edit", as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  resources :weathers, only: [:index] do
    collection do
      post :index
    end
  end

  resources :tweets, only: [:index, :create, :destroy, :edit, :update] do
    collection do
      get :result
    end
  end

  resources :sub_areas, only: [:create] do
    collection do
      delete :delete
    end
  end

  resources :trusts, only: [:create] do
    collection do
      delete :delete
    end
  end
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images

  validates :images, length: { minimum: 0, maximum: 6 }
  validates :text, presence: true

  scope :search, -> (area, date) do
    return if area.blank?
    tweet_like(area).tweet_date(date)
  end

  scope :tweet_like, -> (area) { where('text LIKE ?', "%#{area}%").order("created_at DESC") if area.present? }
  scope :tweet_date, -> (today) { where('created_at >= ?', today).order("created_at DESC") if today.present? }
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # アプリ内投稿機能
  include WeathersHelper
  before_action :set_tweet, only: [:destroy, :edit, :update]

  def index
    @tweets = Tweet.all.order("created_at DESC").page(params[:page]).per(10)
    @tweet = Tweet.new
    @tweet.images.build
  end

  def create
    @tweet = current_user.tweets.build(text: tweet_params[:text])
    if @tweet.save
      unless params[:images].blank?
        params[:images][:image].each do |image|
          if image != nil
            @tweet.images.create!(image: image[1], tweet_id: @tweet_id)
          end
        end
      end
      flash[:notice] = "投稿しました"
      redirect_to tweets_path
    else
      flash[:alert] = "本文は必ず入力してください"
      redirect_to tweets_path
    end
  end

  def destroy
    if @tweet.user_id == current_user.id
      if @tweet.destroy
        flash[:notice] = "削除しました"
        redirect_to tweets_path
      else
        flash[:alert] = "削除に失敗しました"
        redirect_to tweets_path
      end
    end
  end

  def edit
    if @tweet.user_id == current_user.id
    else
      redirect_to tweets_path
    end
  end

  def update
    if @tweet.user_id == current_user.id && @tweet.update(text: update_tweet_params[:text])
      # 画像の更新・追加
      unless params[:images].blank?
        unless params[:images][:image].blank?
          params[:images][:image].each do |img|
            if img[0].to_i < 0 
              @tweet.images.create!(image: img[1], tweet_id: @tweet.id)
            else
              image = Image.find(img[0])
              image.update(image: img[1])
            end
          end
        end
      end
      # 既存画像の削除
      unless params[:delete].blank?
        delete_ids = params[:delete].split(",")
        delete_ids.each do |id|
          image = Image.find(id)
          image.destroy
        end
      end
      flash[:notice] = "変更しました"
      redirect_to tweets_path
    else
      flash[:alert] = "変更に失敗しました"
      redirect_to edit_tweet_path(@tweet.id)
    end
  end

  # weatherページのもっと見るを押した先
  def result
    @area = search_params[:area]
    @tweets = Tweet.tweet_like(@area).page(params[:page]).per(10)
    @tweet = Tweet.new
    @image = @tweet.images.build
  end

  private

  def tweet_params
    params.require(:tweet).permit(:text, 
    images_attributes: [:id, :image, :tweet_id]
    )
  end

  def update_tweet_params
    params.require(:tweet).permit(:text, images_attributes: [:image])
  end

  def search_params
    params.permit(:area)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_search.html.erb
<div class="right-top">
  <h2><%= "#{area}の今日の投稿" %></h2>
  <div class="tweet-result"  >
    <%= render partial: 'tweets/tweet' %>
    <%= paginate @tweets %>
    <div class="more-tweets">
      <%= link_to "#{area}の投稿をもっと見る", result_tweets_path(params: {area: area}) %>
    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<% if @tweets.blank? %>
  <div class="no-result">
    <p><%= @area %>に関する投稿がありません。</p>
  </div>
<% else %>
  <% @tweets.each do |tweet| %>
    <div class="one-tweet">
      <div clas="one-tweet-left">
        <% if tweet.user.image.blank? %>
          <%= image_tag "logo.png" %>
        <% else %>
          <%= image_tag "#{tweet.user.image}" %>
        <% end %>
        <% if user_signed_in? && tweet.user.id != current_user.id %>
          <div class="trust-btn trust-link-<%= tweet.user.id %>">
            <%= render partial: 'trusts/trust', locals: { user: tweet.user } %>
          </div>
        <% end %>
      </div>
      <div class="tweet-info">
        <p class="tweet-name"><%= tweet.user.name %></p>
        <p class="tweet-text"><%= tweet.text %></p>
        <p class="tweet-time"><%= tweet.created_at.strftime("%Y/%m/%d(%a) %H:%M") %></p>
        <div class="tweet-image-box">
          <% if tweet.images %>
            <% tweet.images.each do |image| %>
              <div class="tweet-image">
                <%= link_to "#{image.image.url}", class: "expansion-image" do %>
                  <%= image_tag "#{image.image.url}" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <% if user_signed_in? %>
        <% if tweet.user_id == current_user.id %>
          <div class="tweet-edit">
            <%= link_to "削除", tweet_path(tweet.id), method: :delete %>
            <%= link_to "編集", edit_tweet_path(tweet.id), method: :get %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/tweets/edit.html.erb
<div class="main">
  <h2 class="title">投稿編集</h2>
  <div class="edit-content">
    <div class="edit-user-info">
      <% if @tweet.user.image.blank? %>
        <%= image_tag "logo.png" %>
      <% else %>
        <%= image_tag "#{@tweet.user.image}" %>
      <% end %>
      <p><%= @tweet.user.name %></p>
    </div>
    <%= form_with model: @tweet, url: tweet_path, method: :patch, local: true, class: "edit-form", multipart: true do |f| %>
      <%= f.text_area :text, placeholder: "地域名と一緒に今の天気を共有しよう！", value: @tweet.text, class: "edit-text" %>
      <div class="image-form edit-image-form">
        <%= f.fields_for :images do |i| %>
          <% unless @tweet.images.blank? && i.object[:image] == nil %>
            <div class="already-image-<%= i.object.id %> one-image">
              <%= image_tag i.object.image.url, width: "100%", class: "already-img-prev-#{i.object.id}" %>
              <%= i.label "images[]", for: "edit-image-#{i.object.id}" do %>
                編集
                <%= i.file_field "images[]", name: "images[image][#{i.object.id}]", multiple: true, class: "already-image", id: "edit-image-#{i.object.id}", "data-id": "#{i.object.id}", style: "display:none;" %>
                <%= i.hidden_field :id, value: i.object.id %>
              <% end %>
              <div class="already-image-delete" data-delete="<%=i.object.id%>">
                削除
              </div>
            </div>
          <% end %>
          <%= f.text_field :delete, value: [], name: "delete", type:"hidden" %>
        <% end %>
        <div class="image-prev-all">
        </div>
        <div class="image-form-box edit-form-box">
        </div>
      </div>
      <div class="tweet-btn text-center">
        <%= f.submit "変更" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="main">
  <% if user_signed_in? %>
    <div class="right-content">
      <div class="user-info">
        <% if current_user.image.blank? %>
          <%= image_tag "logo.png" %>
        <% else %>
          <%= image_tag "#{current_user.image}" %>
        <% end %>
        <p><%= current_user.name %></p>
      </div>
      <p class="trust-color user-info-trust">TrustStar獲得数　★ <%= current_user.good_users.length %></p>
      <%= form_with model: @tweet, url: tweets_path, local: true do |f| %>
        <%= f.text_area :text, class: "tweet-form", placeholder: "地域名と一緒に今の天気を共有しよう！" %>
        <div class="image-form">
          <%= f.fields_for :images do |i| %>
            <div class="image-prev-all">
            </div>
            <p>※画像ファイルは1枚ずつ選択してください（最大６枚）</p>
            <div class="image-form-box">
              <div class="image-upload" data-num="0">
                <%= i.file_field "images[]", multiple: true, name: "images[image][-1]", class: "upload_tweet_image", id: 'upload_img_last' %>
                <%= i.hidden_field :id %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="tweet-btn">
          <%= f.submit "投稿" %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="right-content">
      <div class="login-info">
        <p>会員登録して、今の天気を共有しよう <i class= "<%=weather_icon%>"></i></p>
        <%= link_to "新規登録", new_user_registration_path, class: "new-user" %>
        <p>登録済みの方は<%= link_to "ログイン", new_user_session_path, class: "already-user" %></p>
      </div>
    </div>
  <% end %>

  <div class="tweet-area">
    <div class="jscroll">
      <%= render partial: 'tweet' %>
      <%= paginate @tweets %>
    </div>
  </div>
    <div id="popup-background">
    </div>
    <img id="popup-item" src="" >
</div>

app/views/tweets/result.html.erb
<div class="main">
  <% if user_signed_in? %>
    <div class="right-content">
      <% if @area %>
        <h2><%= "#{@area}の今の天気を投稿しよう！" %></h2>
        <div class="user-info">
          <% if current_user.image.blank? %>
            <%= image_tag "logo.png" %>
          <% else %>
            <%= image_tag "#{current_user.image}" %>
          <% end %>
          <p><%= current_user.name %></p>
        </div>
        <%= form_with model: @tweet, url: tweets_path, local: true do |f| %>
          <%= f.text_area :text, class: "tweet-form", placeholder: "地域名と一緒に今の天気を共有しよう！", value: @area %>
          <div class="image-form">
            <%= f.fields_for :images do |i| %>
              <div class="image-prev-all">
              </div>
              <p>※画像ファイルは1枚ずつ選択してください（最大６枚）</p>
              <div class="image-form-box">
                <div class="image-upload" data-num="0">
                  <%= i.file_field "images[]", multiple: true, name: "images[image][-1]", class: "upload_tweet_image", id: 'upload_img_last' %>
                  <%= i.hidden_field :id %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="tweet-btn">
            <%= f.submit "投稿" %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="right-content">
      <div class="login-info">
        <p>会員登録して、今の天気を共有しよう <i class= "<%=@icon%>"></i></p>
        <%= link_to "新規登録", new_user_registration_path, class: "new-user" %>
        <p>登録済みの方は<%= link_to "ログイン", new_user_session_path, class: "already-user" %></p>
      </div>
    </div>
  <% end %>

  <div class="tweet-area">
    <% if @area %>
      <h2><%= "#{@area}の検索結果" %></h2>
      <div class="jscroll">
        <%= render partial: 'tweets/tweet' %>
        <%= paginate @tweets %>
      </div>
    <% end %>
  </div>
    <div id="popup-background">
    </div>
    <img id="popup-item" src="" >
</div>