config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  root 'weathers#index'

  devise_scope :user do
    get "mypage/:id", :to => "users/confirmations#show", as: 'mypage'
    get "profile_edit", :to => "users/registrations#profile_edit", as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  resources :weathers, only: [:index] do
    collection do
      post :index
    end
  end

  resources :tweets, only: [:index, :create, :destroy, :edit, :update] do
    collection do
      get :result
    end
  end

  resources :sub_areas, only: [:create] do
    collection do
      delete :delete
    end
  end

  resources :trusts, only: [:create] do
    collection do
      delete :delete
    end
  end
  
end

app/models/sub_area.rb
class SubArea < ApplicationRecord
  belongs_to :user
  
  validates :area, presence: true
  validates :area, uniqueness: { scope: :user }
end

app/controllers/sub_areas_controller.rb
class SubAreasController < ApplicationController
  before_action :move_to_login, :set_variables

  def create
    sub_area = current_user.sub_areas.build(area: params[:area])
    if sub_area.save
    else
      flash[:alert] = "サブエリアの登録に失敗しました"
    end
  end

  def delete
    if @area != ""
      @sub_area = current_user.sub_areas.find_by(area: @area)
      if @sub_area.destroy
      else
        flash[:alert] = "サブエリアの削除に失敗しました"
      end
    else
      flash[:alert] = "サブエリアの削除に失敗しました"
    end
  end

  private

  def set_variables
    @area = params[:area]
    @area_id = "#sub-area-link-#{ @area }"
  end

  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end

end

app/helpers/sub_areas_helper.rb
module SubAreasHelper
end

app/views/sub_areas/_area_list.html.erb
<% unless sub_areas.blank? %>
  <div class="user-area">
    <ul class="area-list">
      <% unless my_area.blank? %>
        <h2>マイエリア</h2>
        <li class="set-area">
          <%= link_to current_user.my_area, mypage_path(current_user.id) %>
        </li>
      <% end %>
      <h2>サブエリア</h2>
      <% sub_areas.each do |sub| %>
        <li class="set-area">
          <%= link_to sub.area, weathers_path(params: { city: sub.area }), method: :post %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/sub_areas/_sub_area_btn.html.erb
<% if current_user.already_area?(city) %>
  <%= link_to "削除", delete_sub_areas_path(params: { area: city }), method: :delete, remote: true, data: {turbolinks: false} %>
<% else %>
  <%= link_to "登録", sub_areas_path(params: { area: city }), method: :post, remote: true, data: {turbolinks: false}  %>
<% end %>

app/views/sub_areas/_subarea.html.erb
<% unless sub_areas.blank? %>
  <div class="user-area">
    <ul class="area-list">
      <% unless my_area.blank? %>
        <h2>マイエリア</h2>
        <li class="set-area">
          <%= link_to current_user.my_area, mypage_path(current_user.id) %>
        </li>
      <% end %>
      <h2>サブエリア</h2>
      <% sub_areas.each do |sub| %>
        <li class="set-area">
          <%= link_to sub.area, weathers_path(params: { city: sub.area }), method: :post %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/sub_areas/create.js.erb
$("<%= @area_id %>").html('<%= escape_javascript(render("sub_areas/sub_area_btn", city: @area  )) %>');

app/views/sub_areas/delete.js.erb
$("<%= @area_id %>").html('<%= escape_javascript(render("sub_areas/sub_area_btn", city: @area  )) %>')