config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  root 'weathers#index'

  devise_scope :user do
    get "mypage/:id", :to => "users/confirmations#show", as: 'mypage'
    get "profile_edit", :to => "users/registrations#profile_edit", as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  resources :weathers, only: [:index] do
    collection do
      post :index
    end
  end

  resources :tweets, only: [:index, :create, :destroy, :edit, :update] do
    collection do
      get :result
    end
  end

  resources :sub_areas, only: [:create] do
    collection do
      delete :delete
    end
  end

  resources :trusts, only: [:create] do
    collection do
      delete :delete
    end
  end
  
end

app/models/trust.rb
class Trust < ApplicationRecord
  belongs_to :valuer, class_name: 'User', foreign_key: 'valuer_id'
  belongs_to :good_user, class_name: 'User', foreign_key: 'good_user_id'

  validates :valuer, presence: true
  validates :good_user, presence: true
  validates :valuer, uniqueness: { scope: :good_user }
  validate :not_same_user

  def not_same_user
    if valuer == good_user
      errors.add(:valuer, "自分自身は評価できません")
    end
  end

end

app/controllers/trusts_controller.rb
class TrustsController < ApplicationController
  before_action :move_to_login, :set_variables

  def create
    trust = Trust.new(
      valuer_id:     current_user.id,
      good_user_id:  @tweet_user.id
    )
    if trust.save
    else
      flash[:alert] = "TrustStarの登録に失敗しました"
    end
  end

  def delete
    @trust = current_user.valuers.find_by(good_user_id: @tweet_user.id)
    if @trust.destroy
    else
      flash[:alert] = "TrustStarの削除に失敗しました"
    end
  end

  private

  def set_variables
      @tweet_user = User.find(params[:tweet_user])
      @trust_id = ".trust-link-#{ @tweet_user.id }"
  end

  def move_to_login
    redirect_to new_user_session_path unless user_signed_in?
  end

end

app/helpers/trusts_helper.rb
module TrustsHelper
end

app/views/trusts/_trust.html.erb
<% if current_user.already_good?(user) %>
  <div class="trust-length">
    <p class="trust-color">★ <%= user.good_users.length %></p>
    <div class="trust-info">
		  <p class="trust-info__text">TrustStarとは...<br>
      ユーザーからの信頼度です。<br>
      投稿者が信頼できると感じたら、<br>
      TrustStarを贈呈しよう！</p>
	  </div>
  </div>
  <%= link_to "TrustStar没収", delete_trusts_path(params: { tweet_user: user.id }), method: :delete, remote: true, data: {turbolinks: false} %>
<% else %>
  <div class="trust-length">
    <p class="trust-color">☆ <%= user.good_users.length %></p>
    <div class="trust-info">
		  <p class="trust-info__text">TrustStarとは...<br>
      ユーザーからの信頼度です。<br>
      投稿者が信頼できると感じたら、<br>
      TrustStarを贈呈しよう！</p>
	  </div>
  </div>
  <%= link_to "TrustStarを渡す", trusts_path(params: { tweet_user: user.id }), method: :post, remote: true, data: {turbolinks: false}  %>
<% end %>

app/views/trusts/create.js.erb
$("<%= @trust_id %>").html('<%= escape_javascript(render("trusts/trust", user: @tweet_user  )) %>');

app/views/trusts/delete.js.erb
$("<%= @trust_id %>").html('<%= escape_javascript(render("trusts/trust", user: @tweet_user, count: @tweet_user.good_users.length  )) %>');