config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  root 'weathers#index'

  devise_scope :user do
    get "mypage/:id", :to => "users/confirmations#show", as: 'mypage'
    get "profile_edit", :to => "users/registrations#profile_edit", as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  resources :weathers, only: [:index] do
    collection do
      post :index
    end
  end

  resources :tweets, only: [:index, :create, :destroy, :edit, :update] do
    collection do
      get :result
    end
  end

  resources :sub_areas, only: [:create] do
    collection do
      delete :delete
    end
  end

  resources :trusts, only: [:create] do
    collection do
      delete :delete
    end
  end
  
end

app/views/layouts/_flash.html.erb
<% unless flash[:notice].blank? && flash[:alert].blank? %>
  <div class="flash-message">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: key) %>
    <% end %>
  </div>
<% end %>

app/views/layouts/_top_page.html.erb
<div class="top">
  <div class="top__app-name">
    <h2>Let's sharing weather!</h2>
    <h1>Link Weather</h1>
  </div>

  <div class="top__heading">
    <h3>今の天気を確認しよう！</h3>
    <div class="top__heading__info">
      <div class="search-box">
        <%= form_with url: weathers_path, method: :post, local: true, class: "weather-search-form" do |f| %>
          <%= f.text_field :city, class: "area-search", placeholder: "地域を入力" %>
          <div class="search-btn">
            <%= button_tag type: "submit" do %>
              <i class="fa fa-search">検索</i>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="top-info-contents">
        <div class="top-info-contents__content">
          <h4>天気予報</h4>
          <p>３時間毎の３日間の予報を表示<br>
          不快指数で快適さをチェック！</p>
        </div>
        <div class="top-info-contents__content">
          <h4>本日の投稿</h4>
          <p>LinkWeather内で投稿された天気情報を表示<br>
          万が一天気予報が外れていても、その場にいるユーザーを通じてリアルタイムの情報を取得できる！</p>
        </div>
        <div class="top-info-contents__content">
          <h4>Twitter検索</h4>
          <p>Twitterから天気に関するツイートを取得<br>
          LinkWeather内で情報が不足していても大丈夫！</p>
        </div>
      </div>
    </div>
  </div>

  <div class="top__heading">
    <h3>今の天気を共有しよう！</h3>
    <div class="top__heading__info">
      <div class="top-link">
        <%= link_to tweets_path do %>
          <i class= "<%=weather_icon%>">  Let's sharing wether!</i>
        <% end %>
      </div>
      <div class="top-info-contents">
        <div class="top-info-contents__content">
          <h4>今の天気を発信</h4>
          <p>今いる場所と今の天気を投稿して、みんなに教えてあげよう！<br>
          画像も一緒に投稿できるよ！
          綺麗な空を共有しよう☀︎<br>
          混雑状況などもgood！</p>
          <p class="attention">※投稿には、会員登録が必要です。</p>
        </div>
        <div class="top-info-contents__content">
          <h4>投稿された情報を閲覧</h4>
          <p>みんなが投稿した天気情報を見てみよう！<br>
          もしかしたら天気予報とは真逆の天気かも？</p>
        </div>
      </div>
    </div>
  </div>

  <div class="top__heading">
    <h3>もっと使いやすくしよう！</h3>
    <div class="top__heading__info">
      <div class="top-link">
        <%= link_to "新規会員登録", new_user_registration_path %>
      </div>
      <div class="top-info-contents">
        <div class="top-info-contents__content">
          <h4>情報発信</h4>
          <p>ログインすると天気情報を投稿できるようになるよ<br>
          あなたの投稿が誰かの役に立つ！<br>
          天気情報以外にも、夕日や虹の写真が撮れたらみんなに自慢しちゃおう！</p>
        </div>
        <div class="top-info-contents__content">
          <h4>よく行くエリアを登録</h4>
          <p>ログインするとあなたが住んでいる場所はもちろん、<br>
          よく行く場所も登録できるようになるよ！<br>
          マイページからすぐに確認できるので、検索の手間が省ける！</p>
        </div>
      </div>
    </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkWeather</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://platform.twitter.com/widgets.js', charset: 'utf-8', async: 'async' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=yes">
  </head>

  <body>
    <header>
      <div class="logo-box">
        <%= link_to root_path do %>
          <%= image_tag 'logo.png', class: "logo-img" %>
        <% end %>
      </div>
      <div class="header-right">
        <div class="search-box">
          <%= form_with url: weathers_path, method: :post, local: true do |f| %>
            <%= f.text_field :city, class: "area-search", placeholder: "天気を確認したい地域を入力" %>
            <div class="search-btn">
              <%= button_tag type: "submit" do %>
                <i class="fa fa-search"></i>
              <% end %>
            </div>
          <% end %>
        </div>
        <label for="mobile-user-menu" class="mobile-menu-label">Menu</label>
          <input type="checkbox" id="mobile-user-menu"/>
        <ul class="header-right-under">
          <div class="header-right-under-tweet">
            <div class="tweet-box">
              <li><%= link_to "Let's sharing wether!", tweets_path %></li>
            </div>
          </div>
          <div class="header-right-under-user">
            <% if user_signed_in? %>
              <div class="mypage-box">
                <li><%= link_to "my page", mypage_path(current_user) %></li>
              </div>
              <div class="logout-box">
                <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
              </div>
              <div class="setting-box">
                <div class="setting-btn">
                  <li>
                    <%= link_to profile_edit_path do %>
                      <i class="fa fa-cog"></i>
                      <p>設定</p>
                    <% end %>
                  </li>
                </div>
              </div>
            <% else%>
              <div class="session-box">
                <div class="login-box">
                  <li><%= link_to "login", new_user_session_path %></li>
                </div>
                <div class="signup-box">
                  <li><%= link_to "signup", new_user_registration_path %></li>
                </div>
              </div>
            <% end %>
          </div>
        </ul>
      </div>
    </header>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <footer>
      <%= image_tag "cityblack.png" %>
    </footer>
  </body>
</html>